name: Build and Merge Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - luci-smartdns-dev

jobs:
  build_and_merge:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: Check if branch exists and checkout
    - name: Fetch and Checkout Branch
      run: |
        git fetch --all
        if git show-ref --verify --quiet refs/remotes/origin/luci-smartdns-dev; then
          git checkout -b luci-smartdns-dev origin/luci-smartdns-dev
        else
          echo "Branch luci-smartdns-dev does not exist. Falling back to main branch."
          git checkout main
        fi

    # Step 3: Attempt to merge
    - name: Merge Branch
      run: |
        git merge main || echo "Merge conflicts detected. Please resolve manually."
        if [ -f "$(git ls-files -u | head -n 1)" ]; then
          git status
          exit 1
        fi

    # Step 4: Push changes
    - name: Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin luci-smartdns-dev || echo "Push failed. Please check permissions or conflicts."

    # Step 5: Handle merge conflicts (optional)
    - name: Merge Conflicts Handling
      if: failure()
      run: |
        echo "There are unresolved merge conflicts. Exiting workflow."
        git status
        exit 1
